services:
  postgres:
    image: postgres:16
    container_name: fyndly-postgres
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - fyndly_postgres_data:/var/lib/postgresql/data

volumes:
  fyndly_postgres_data:
