export enum ApiErrorCode {
  VALIDATION_ERROR = 'validation_error',
  VALIDATION_INVALID = 'validation_invalid',
  VALIDATION_EMAIL = 'validation_email',
  VALIDATION_MIN_LENGTH = 'validation_min_length',
  PASSWORD_DO_NOT_MATCH = 'passwords_do_not_match',
  EMAIL_ALREADY_EXISTS = 'email_already_exists',
  USERNAME_ALREADY_EXISTS = 'username_already_exists',
  INVALID_CREDENTIALS = 'invalid_credentials',
  USER_NOT_FOUND = 'user_not_found',
  INVALID_VERIFICATION_CODE = 'invalid_verification_code',
  VERIFICATION_CODE_EXPIRED = 'verification_code_expired',
  EMAIL_NOT_VERIFIED = 'email_not_verified',
  VERIFICATION_CODE_RESEND_TOO_SOON = 'verification_code_resend_too_soon',
  RESET_PASSWORD_CODE_EXPIRED = 'reset_password_code_expired',
  INVALID_RESET_PASSWORD_CODE = 'invalid_reset_password_code',
  RESET_PASSWORD_CODE_RESEND_TOO_SOON = 'reset_password_code_resend_too_soon',
  NEW_PASSWORD_MUST_BE_DIFFERENT = 'new_password_must_be_different',
}
